#!/usr/bin/env python3
"""Normalize the EOF newline of patches generated by `pnpm patch-commit`.

Why this exists (verified 2026-10-05, pnpm 11.20.0)
---------------------------------------------------
pnpm's patch applier rebuilds a *modified* file by joining its lines with "\n"
and never re-adds the file's final newline, so a patch produced by
`pnpm patch-commit` reproduces the target file byte-for-byte EXCEPT that the
last newline is missing. Newly added files (`diff --git ... @@ -0,0 +1,N @@`)
go through a different code path and DO keep their trailing newline.

Practical impact: `tether-patches-20260920/install-tether-build.sh` compares
sha256 prefixes of the node_modules files. A patch that drops one trailing
newline silently moves the hash and makes the installer `exit 2`. Rather than
weaken the check, this script makes the patch reproduce the intended bytes.

How: it appends one empty added line to the LAST hunk of each listed file
(extending that hunk to EOF with context lines first when the hunk stops before
EOF). Because the applier joins the resulting line array with "\n", the extra
empty final element re-creates the trailing newline.

Usage
-----
  scripts/fix-pnpm-patch-eof.py <patchfile> <relpath>=<patchedfile> [<relpath>=<patchedfile> ...]

Example
-------
  scripts/fix-pnpm-patch-eof.py patches/tether-agent-core@0.1.21.patch \
      dist/checkpoint.js=$HOME/tether-patches-20260922/patched/checkpoint.js

Idempotent: already-normalized files are skipped (prints "skip (already ok)").
Targets whose canonical file has no trailing newline are skipped as well.
"""

from __future__ import annotations

import re
import sys

HUNK_RE = re.compile(r"(?m)^@@ -(\d+),(\d+) \+(\d+),(\d+) @@(.*)$")


def lines_of(path: str) -> list[str] | None:
    data = open(path, encoding="utf-8").read()
    if not data.endswith("\n"):
        return None  # canonical file has no trailing newline -> nothing to fix
    return data.split("\n")[:-1]


def split_sections(src: str):
    starts = [m.start() for m in re.finditer(r"(?m)^diff --git ", src)]
    if not starts:
        return src, []
    head = src[: starts[0]]
    secs = [
        src[s : (starts[k + 1] if k + 1 < len(starts) else len(src))]
        for k, s in enumerate(starts)
    ]
    return head, secs


def fix_section(sec: str, relpath: str, canonical: list[str]) -> str:
    hunks = list(HUNK_RE.finditer(sec))
    if not hunks:
        raise SystemExit(f"{relpath}: patch section has no hunks")
    last = hunks[-1]
    old_start, old_count, new_start, new_count = map(int, last.groups()[:4])
    expected = len(canonical) - new_start + 2  # new_count once the fix is in
    if new_count == expected:
        print(f"  {relpath}: skip (already normalized)")
        return sec
    tail = canonical[new_start + new_count - 1 :]
    if len(tail) == 0 and new_start + new_count - 1 != len(canonical):
        raise SystemExit(
            f"{relpath}: hunk/new-file line accounting mismatch "
            f"(new_start={new_start}, new_count={new_count}, lines={len(canonical)})"
        )
    body = sec[last.end() :]
    if "@@" in body:
        raise SystemExit(f"{relpath}: last hunk is not the final hunk of the section")
    header = f"@@ -{old_start},{old_count + len(tail)} +{new_start},{new_count + len(tail) + 1} @@{last.group(5)}"
    fixed = body + "".join(" " + line + "\n" for line in tail) + "+\n"
    print(
        f"  {relpath}: +{new_count} -> +{new_count + len(tail) + 1} "
        f"(tail context {len(tail)} lines, +1 empty EOF line)"
    )
    return sec[: last.start()] + header + fixed


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2
    patch_path = argv[1]
    targets: dict[str, list[str] | None] = {}
    for spec in argv[2:]:
        rel, _, canon = spec.partition("=")
        if not canon:
            raise SystemExit(f"bad target spec (want relpath=file): {spec}")
        targets[rel] = lines_of(canon)
    src = open(patch_path, encoding="utf-8").read()
    head, secs = split_sections(src)
    out = []
    seen = set()
    for sec in secs:
        m = re.match(r"diff --git a/(\S+) b/(\S+)", sec)
        rel = m.group(2) if m else None
        if rel in targets:
            seen.add(rel)
            canonical = targets[rel]
            if canonical is None:
                print(f"  {rel}: skip (canonical file has no trailing newline)")
            elif not sec.endswith("\n"):
                raise SystemExit(f"{rel}: patch section does not end with a newline")
            else:
                sec = fix_section(sec, rel, canonical)
        out.append(sec)
    missing = set(targets) - seen
    if missing:
        raise SystemExit(f"targets not found in patch: {sorted(missing)}")
    open(patch_path, "w").write(head + "".join(out))
    print(f"wrote {patch_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
